### ISSUE TITLE
sqlite database locked for Worker thread

### ISSUE THREAD

**Issue by watarat** [inventree/inventree-docs#124]
I've had Inventree runnng untouched in an AWS service for 6 months or so, and have pulled it back into a Ubuntu VM on my local Windoze machine (local sqlite3) for various reasons, so the 'Worker' thread part of the system is new to me. 
When I run it, I get a "database is locked" error message.
I'm not clear on just what services the Worker thread provides - but the Inventree frontend seems largely functional without it - or at least with it limping along? 
Any suggestions of whether to worry? - or continue poking around  ( I do have some (perhaps corrupt) data base issues) 

```
03:07:24 [Q] ERROR database is locked
03:07:27 [Q] ERROR database is locked
03:07:27 [Q] ERROR Failed [carbon-maine-skylark-steak] - database is locked : Traceback (most recent call last):
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/richard/inventree-env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

.......
03:14:26 [Q] WARNING reincarnated worker Process-1:2 after timeout
03:14:26 [Q] INFO Process-1:7 ready for work at 3528

```

**Comment by watarat** [comment]
I've completed a new install into a second VM and noticed a different directory structure, (I've copied over database and part files etc),  and the locked data base problem seems to go away - so - the original query is probably not worth chasing - suspect its a consequence of too much mucking about with updates etc.
Only remaining odd bits are a warning and 1 error from the Worker.
Suspect they are not terminal. :)


```
08:54:49 [Q] INFO Processed [fix-hotel-eighteen-delaware]
08:55:19 [Q] INFO Enqueued 304
08:55:19 [Q] INFO Process-1 created a task from schedule [InvenTree.tasks.heartbeat]
08:55:19 [Q] INFO Process-1:1 processing [sad-harry-victor-item]
Could not perform heartbeat task - App registry not ready
/home/inventree/env/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Task.started received a naive datetime (2021-06-22 08:25:19.582200) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"

```

**Comment by SchrodingersGat** [comment]
@watarat glad you got it sorted. In general I'd advise against using SQLite - instead look at MySQL or PostgreSQL as they are far more robust.

**Comment by watarat** [comment]
Ok - I'll look at that.
Any comment on the heartbeat task & DateField warning?

**Comment by SchrodingersGat** [comment]
You can safely ignore that warning :) It's on my list to fix but it's nothing to worry about.

**Comment by watarat** [comment]
👍
Main reason for sticking with sqlite is (apart from 'my needs are small' :),  is that I want a simple backup procedure.
Having the files and the database in a separate user's space (inventree) is already a bit awkward but managable.
Is there any info/suggestion - pages or discussion that I've missed - as a source of ideas - for simple backup??

**Comment by SchrodingersGat** [comment]
Recommended backup procedure is somewhat "out of scope" for the project - although I'm sure there are plenty of good resources for your database of choice.

You could also look at backing up to an "agnostic" JSON file using the `export_records` command - https://inventree.readthedocs.io/en/latest/start/migrate/

**Comment by watarat** [comment]
Also need to backup all of the media files and label layouts etc - I'll probably do it somewhat manually for the moment.
Thanks for pointer!!
