### ISSUE TITLE
Feature Request - Part Label

### ISSUE THREAD

**Issue by watarat** [inventree/inventree-docs#129]
I would find it very useful to be able to print labels for a PART (as distinct from STOCK).
I can see that there is partial support for that - the option to print a part label is in the GUI but there doesn't seem to be a back end for it ??

Use case for me - is that if I don't have any stock of an item - I am unable to utilise the App scan function.
So - typically for me - when I receive new parts - or am simply replenishing parts I've run out of - it would be useful to have a barcode to scan. (This could be either on an empty bag, or placeholder card - in the appropriate stock location.)
(Guess I am sort of thinking of the PART as being the parent of STOCK, and in the event of no stock - I can use the parent as an identifier)

So then when an order comes in - I can just scan the bag/card and add stock.
(Not sure if that functionality is within the App yet - given there are no stock labels to scan). 

Rationale for this goes along the line of..
If I run out of something - say 1k resistors - if I go looking in the logical place (Resistor Box) - then there is nothing there - oops - maybe they are somewhere else - or put back out of order - better rifle through the whole box, look elsewhere. etc.
So I prefer to have something to mark that they are supposed to be there. i.e. I prefer to find an empty bag (with a label)- rather than find nothing ;)

Being able print a Part label sorta solves this for me I think - not sure if this is the right place to have this discussion - point me elsewhere if not :)
R

**Comment by eeintech** [comment]
@watarat You can post this kind of feature request here instead: https://github.com/inventree/InvenTree/issues

This repo is for documentation :smiley:

**Comment by watarat** [comment]
Thanks - Reposted to Inventree :)
