### ISSUE TITLE
Removal of Part Parameter Templates

### ISSUE THREAD

**Issue by stijnloeys** [inventree/inventree-docs#130]
Hey, 

Is there a way that a Part Parameter Template could be removed from the list?
I accidentaly messed up a few times, typing data in the unit space, but now there is no way to reuse that name with the correct units.

Kind Regards

**Comment by eeintech** [comment]
@stijnloeys This repository is for the documentation of the InvenTree project, you can post your question here: https://github.com/inventree/InvenTree/issues

Hint about this: yes it is possible in the Settings, click on the red garbage can icon on the right of the Part Parameter Template you'd like to delete

![image](https://user-images.githubusercontent.com/4020546/124762072-7ae8c000-df00-11eb-9324-618e98fc73dd.png)
