### ISSUE TITLE
Generating translations

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-docs#156]
I might be mistaken on that one but I believe `inv translate` needs to be ran at each update, else the language dropdown looks like this:

![image](https://user-images.githubusercontent.com/4020546/129581772-d17d3b07-95b0-4b7f-85e8-f522656ebce6.png)

After `inv translate`:

![image](https://user-images.githubusercontent.com/4020546/129581995-a5eb67d8-04f6-43b9-8253-32897a200adc.png)

Or is it only my setup that is not auto-translating when running `inv update`?

**Comment by SchrodingersGat** [comment]
The file `locale_stats.json` is where the translation stats are stored. I guess this file is only properly being updated when you run `invoke translate`...

Perhaps we should ensure that `translate` is called as part of the `update` step.

@matmair any thoughts here on a different approach?

**Comment by eeintech** [comment]
@SchrodingersGat Now I'm getting all those `*.mo` and `*.po` files showing up in Git...

![image](https://user-images.githubusercontent.com/4020546/130119677-76f4e9ec-c053-43e9-a735-3d0a6617a9a0.png)

**Comment by matmair** [comment]
@eeintech yes that file is generated with the translations. I will try to work that into the translation action.

The translate command generates fresh translation reference files for all languages and compiles them - you can disregard / reset them.

**Comment by eeintech** [comment]
That's what I thought, it is just quite annoying to have to do this each time after an `inv update` :confused:

**Comment by matmair** [comment]
@eeintech I think we need to close this manually after the PR is through.

**Comment by eeintech** [comment]
Can do! 👍
