### ISSUE TITLE
Add CI checking

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#16]
Add travis CI script to ensure that the docs actually build!

**Comment by eeintech** [comment]
Travis would be nice but what also a [webhook to the ReadTheDocs build status](https://docs.readthedocs.io/en/stable/webhooks.html)?

To get something like this on PRs:

![image](https://user-images.githubusercontent.com/4020546/96597520-8e40f600-12b3-11eb-91c8-bef00e45fd12.png)

**Comment by SchrodingersGat** [comment]
There is already a status badge in README.md

![image](https://user-images.githubusercontent.com/10080325/97120953-18cf9c80-176f-11eb-9a14-8d1f08346cf4.png)

**Comment by eeintech** [comment]
That's nice but I was more referring to the PR CI system, unless Travis CI can be used to reproduce RTD build setup.

**Comment by SchrodingersGat** [comment]
Ah yes fair enough distinction

**Comment by eeintech** [comment]
@SchrodingersGat Have you taken a look into the webhooks? https://docs.readthedocs.io/en/stable/webhooks.html
I think this need to be setup directly on your RTD account. Would be nice to just get the build result directly from RTD, no?

**Comment by eeintech** [comment]
The new hook works well! It's nice to be able to see the result of the build before the merge, like: https://inventree--30.org.readthedocs.build/en/30/

**Comment by mmideveloper** [comment]
@SchrodingersGat @eeintech is there any way of contacting you outside of github with bugs / features or would you like it kept in here?

**Comment by eeintech** [comment]
@mmideveloper For bugs and features yes please open an issue in the main InvenTree repository: https://github.com/inventree/InvenTree/issues

There is no external contact mean as of now, I think Oliver wants to keep all the information centralized on GitHub 😉

**Comment by SchrodingersGat** [comment]
@mmideveloper as @eeintech says, issues should be raised on github :) thanks
