### ISSUE TITLE
Version and code source contribution (dev/prod)

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-docs#168]
- [x] Update "Releases" doc with information on the meaning of the version and two different branches (master/dev vs stable/prod)
- [x] Add subsection to contribution section to explain the new PR flow

References:
https://github.com/orgs/inventree/teams/triage/discussions/4/comments/15
https://github.com/orgs/inventree/teams/triage/discussions/4/comments/24

**Comment by SchrodingersGat** [comment]
Docs have been updated

**Comment by eeintech** [comment]
Thanks @SchrodingersGat !
