### ISSUE TITLE
Complete documentation for reports

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#171]
- https://inventree.readthedocs.io/en/latest/report/test/#test-report
- https://inventree.readthedocs.io/en/latest/report/order/
- https://inventree.readthedocs.io/en/latest/report/report/#sales-order
- https://inventree.readthedocs.io/en/latest/report/build/#build-filters
- https://inventree.readthedocs.io/en/latest/stock/test/#reporting

**Comment by eeintech** [comment]
Should this section: https://inventree.readthedocs.io/en/latest/stock/test/#reporting
Be referring to https://inventree.readthedocs.io/en/latest/report/report/
and the TODO message removed?

**Comment by SchrodingersGat** [comment]
@eeintech yes I think you are correct here

**Comment by eeintech** [comment]
Thanks, I made that correction in #258

**Comment by eeintech** [comment]
(didn't mean to close the issue with PR)

**Comment by SchrodingersGat** [comment]
Reports documentation has been significantly updated. Any particular problems should be addressed with a new issue.
