### ISSUE TITLE
Documentation for "stocktake"

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#172]
- https://inventree.readthedocs.io/en/latest/stock/stocktake/

Currently just a TODO section

**Comment by eeintech** [comment]
Isn't is just the "Count Stock" menu option?
https://inventree.readthedocs.io/en/latest/stock/adjust/#count-stock

**Comment by SchrodingersGat** [comment]
Stocktake is a separate thing, but it hasn't been implem yet. We should delete this page for now.
