### ISSUE TITLE
Add page or tab to document global settings and their impact on the UI

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-docs#180]
It's currently very difficult to find information on those, maybe add a page named "Global Settings" after "Admin Interface" under the "Admin" tab?

Most settings are self-explanatory once found, but the existence of each setting is still not obvious. This would be a way to quickly find out about them, using the doc.

**Comment by SchrodingersGat** [comment]
[Most of these are documented now under the "global settings" pge](https://inventree.readthedocs.io/en/latest/settings/global/)

**Comment by eeintech** [comment]
Nice thanks!
