### ISSUE TITLE
Add documentation for "merging" stock items

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#218]
Ref: https://github.com/inventree/InvenTree/issues/346

Once the new feature is implemented, it will need to be documented!

- Process
- Requirements
- Edge cases
- Exceptions

**Comment by eeintech** [comment]
@SchrodingersGat For the process, is it about explaining how to merge, the merge form and the result of the merge?

![image](https://user-images.githubusercontent.com/4020546/149143961-6ab76e9c-3483-41c4-856f-02569d63cabc.png)

I do not know what the requirements, edge cases (tracked items?) and exceptions are... could you please let me know and I can put those in the docs.

**Comment by SchrodingersGat** [comment]
A simple introductory paragraph, and some screenshots of examples should suffice, I think.

Regarding "requirements" - see here: https://github.com/inventree/InvenTree/blob/7f31e08c56293ddc663292bec2cf2163bbb2e059/InvenTree/stock/models.py#L1165

**Comment by eeintech** [comment]
Thanks @SchrodingersGat, will do
