### ISSUE TITLE
Add documentation for plugin mixins

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#221]
Each builtin mixin class needs to be documented

**Comment by matmair** [comment]
Settings, Url, Navigation and App are documented [here](https://inventree--192.org.readthedocs.build/en/192/extend/plugins/integration/#mixins)

**Comment by eeintech** [comment]
@matmair Wan't to get on that one with your deeper knowledge of plugins?

**Comment by matmair** [comment]
@eeintech i documented my mixins, will have to read into the others before doing that for others. In general docstrings seem to be a better way for docs imo.

**Comment by SchrodingersGat** [comment]
Working on this now

**Comment by eeintech** [comment]
Nice thanks!
