### ISSUE TITLE
Issue when installing pip3 packages on env

### ISSUE THREAD

**Issue by huseyinkogo** [inventree/inventree-docs#223]
Hey,

Love the software, wanted to install Inventree on my RPI 4, however need help installing on pip3 install psycopg2 pgcli on rp4 server, getting the errors please see attached screenshot.

I'm stuck on this part of the guide https://inventree.readthedocs.io/en/latest/start/install/#install-python-bindings

Also tried pip3 install mysqlclient mariadb it failed too.

And on my next new session, how can enter (env) through the cli 

![image_2022-01-10_114456](https://user-images.githubusercontent.com/76049382/148707926-a0411f2e-5031-4649-998f-ef3687aebefd.png)

**Comment by eeintech** [comment]
Hello @huseyinkogo 

You are posting in the documentation repository, please post your issue here instead: https://github.com/inventree/InvenTree/issues
