### ISSUE TITLE
Add "blog" section

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#234]
Separate to release page, a blog page for updates on new features, "in the news" etc

**Comment by matmair** [comment]
@SchrodingersGat I made a mockup for a bigger website some months ago - maybe useful for a long term goal?
https://matmair.github.io/home.invenhost.com/

**Comment by SchrodingersGat** [comment]
Yeah that's nice. It would be great for inventree.org to display that

**Comment by eeintech** [comment]
Cool concept, would make it a legit project :+1:

**Comment by matmair** [comment]
I think we should discuss what to but on there but would love to do the site itseld.
The pages are done in yaml / markdown just like mkdocs. I will give you access to the source code, we should transfer it to the inventree-org when you deem it ready.

**Comment by SchrodingersGat** [comment]
Sounds like a great thing to look at after the 0.6.0 release!

**Comment by matmair** [comment]
For sure!

**Comment by SchrodingersGat** [comment]
Closing out this issue, makes much more sense for this to be on the website rather than the docs pages
