### ISSUE TITLE
Not possible to create a New Parameter Template?

### ISSUE THREAD

**Issue by Stephano120** [inventree/inventree-docs#238]
The doc here::
https://inventree.readthedocs.io/en/latest/part/parameter/#_
Says:

> Create Template¶
> A Parameter Template is required for each part parameter.
> 
> To create a template:
> 
> navigate to the "Settings" page
> click on the "Parts" tab
> scroll down to the "Part Parameter Templates" section
> click on the "New Parameter" button
> fill out the Create Part Parameter Template form: Name (required) and Units (optional) fields
> finally click on the "Submit" button.

Using the demo version available online (thanks for this, btw), and by clicking on a part, say, https://demo.inventree.org/part/82/ (1551ABK), then on the green button "New Parameter", I can chose a (predefined) template, and set a value, **but** assuming I need to add a parameter "Color" for instance, then, it seems it is required to define a new  _Parameter Template_  first, 

Question is: where and how is it supposed to be done?
I've looked for this everywhere. Didnt find anything. Am I blind?

**Comment by eeintech** [comment]
@Stephano120 You have quoted the steps and URL which explains the process to create a Parameter Template.
Follow the steps and you will be able to create a Parameter Template for "Color".
Then navigate to the demo part and you will be able to select it when creating a new parameter.

**Comment by matmair** [comment]
Hi there @Stephano120 !
This repo is only for doc related stuff, if you have questions about the software please use inventree/inventree. We have issues and discussions enabled there.

Regarding your question: As stated in the doc snippet you posted you have to create the parameter template before being able to use it. You need to go to the [seetings](https://demo.inventree.org/settings/#) and there to  parts and add the template first.

**Comment by matmair** [comment]
> @Stephano120 You have quoted the steps and URL which explains the process to create a Parameter Template. Follow the steps and you will be able to create a Parameter Template for "Color". Then navigate to the demo part and you will be able to select it when creating a new parameter.

Hi 👋

**Comment by Stephano120** [comment]
Thanks for your answers but I'm quite sure that if you try to add a Parameter Template on your side, using the demo available online, you won't succeed.
"You need to go to the settings and there to parts and add the template first."
Well...Settings gives me this: 
![image](https://user-images.githubusercontent.com/49557719/151430197-0c2fe601-bab1-4b97-be7e-a16434e3bdd0.png)

**Comment by matmair** [comment]
@Stephano120 you need to be an admin to access the admin settings. You only see the user settings right now.

**Comment by Stephano120** [comment]
@matmair Ha !! indeed ! Thanks ! Thought "allaccess/nolimits" was enough...and that the rows below where for more restrictive accounts type. Works better now :D

**Comment by eeintech** [comment]
Good point @Stephano120 only admins have access to those settings and as @matmair and I are always working on the admin side of things we tend to forget that!
