### ISSUE TITLE
Mobile app code access?

### ISSUE THREAD

**Issue by provenvelocity** [inventree/inventree-docs#255]
How do we get access to the mobile app also? Is it open source or do we need to license it to edit the code?

**Comment by SchrodingersGat** [comment]
@provenvelocity I am in the process of open sourcing the app code. Should be available (here) in the next few weeks.

**Comment by provenvelocity** [comment]
Nice, let me know if you need help.

**Comment by SchrodingersGat** [comment]
@provenvelocity https://github.com/inventree/inventree-app
