### ISSUE TITLE
Docs for notifications

### ISSUE THREAD

**Issue by matmair** [inventree/inventree-docs#256]
Add docs for new notifications https://github.com/inventree/InvenTree/pull/2372

**Comment by SchrodingersGat** [comment]
@matmair could you please have a look at updating the notifications docs for the imminent release?

**Comment by matmair** [comment]
@SchrodingersGat what else would you like to be documented additional to https://inventree--292.org.readthedocs.build/en/292/part/notification/

**Comment by SchrodingersGat** [comment]
That link shows information on what notifications can be sent, but I don't think we have any overall documentation of the notification system itself.

I'd like to see a (brief) introduction to notifications:

- Enabling the CoreNotifcation plugin
- Activating email notifications
- adding other notification methods via plugins

It only needs to be a few short paragraphs to match the refactor work you did recently

**Comment by SchrodingersGat** [comment]
I'm happy to bump this to the next candidate
