### ISSUE TITLE
Add support for Kicad BOM import

### ISSUE THREAD

**Issue by lukh** [inventree/inventree-docs#261]
Hello ! 
Just discovered Inventree, it looks really good :)

I was wondering about the complexity of writing a "plugin" that can import KiCAD BOM directly, instead of having to parse and convert the BOM specificly to Inventree format...
(I will easily write a script that convert the standard Kicad BOM to the Inventree BOM Format, that's no big deal..)
It could be run externally before importing, but where the fun ?

**Comment by eeintech** [comment]
Hello @lukh 

This is the repository for the documentation.
Please open a feature request here: https://github.com/inventree/InvenTree/issues

Thanks!
