### ISSUE TITLE
Add doc for Parts and Categories global settings

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-docs#268]
It's currently missing:

![image](https://user-images.githubusercontent.com/4020546/164282363-8d01b07f-594c-4fa5-9eaa-2103658cc239.png)

**Comment by SchrodingersGat** [comment]
Thanks. Do you have any time to address this one?

**Comment by eeintech** [comment]
> Thanks. Do you have any time to address this one?

I might in the coming days 😃

**Comment by eeintech** [comment]
@SchrodingersGat Ready! See #273
