### ISSUE TITLE
Automated builds not working

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#27]
It would appear that pushing to master does *not* automatically start a new build, they have to be triggered manually..

**Comment by eeintech** [comment]
@SchrodingersGat I think this issue and #16 could be fixed with the webhook: https://docs.readthedocs.io/en/latest/webhooks.html#i-was-warned-i-shouldn-t-use-github-services

**Comment by SchrodingersGat** [comment]
Yep, looks like it is working now after setting up the webhook. I just pushed a small whitespace chance to README.md and it triggered a build!
