### ISSUE TITLE
Track stock vs Unstracked Stock

### ISSUE THREAD

**Issue by spectre-ns** [inventree/inventree-docs#275]
I'm evaluating using this for a small company I work for I find it odd that the build process excluded tracked stock which must then be allocated after the object has been places in inventory. 

Doesn't this result in having incomplete parts in inventory after the build phase is complete when consuming tracked subcomponents?

**Comment by spectre-ns** [comment]
Nevermind

**Comment by matmair** [comment]
@spectre-ns did you find your answer or do you want a hint?

**Comment by spectre-ns** [comment]
No I figured it out. Had a hard time figuring it out because it wasn't immediately evident in the documentation.

**Comment by matmair** [comment]
@spectre-ns if you have ideas on how it could be better we would appreciate an issue (just pointing out the page that is uncertain is also fine).
We are so deep into the details of building huge, subassembly ridden assemblies that we sometimes overlook the easy starter things ;-)

**Comment by spectre-ns** [comment]
@matmair Thanks for the offer. The docs are pretty barebones but I don't think there is a specific page that needs updating. I understand you're probably not working on this full time and appreciate your efforts on this product. The roadmap is particularly exciting. Considering I'm thinking about employing this at my company I might try to get some funding if I knew what you're using it for. :) Again I love that you've made a bare bones inventory system when sprawling ERPs are the normal.

**Comment by matmair** [comment]
@matmair we are more a group of devs, not really documentators.
For SMEs the project should be a good fit (plus you can easily extend it) - the core team is deploying it in their various companies. With time you will discover all the settings that turn InvenTree into a small PLM but the default settings are kept simple. You can for example do price history, scheduling, production-line or webshop-integration.

**Comment by spectre-ns** [comment]
Awesome! We are a start up building ~50 units a year based on electronic and optical components so I'm thinking it is a good fit. If we find long term use for the project I'll be sure to contribute personally contribute some dev time! :)
