### ISSUE TITLE
Update "install" documentation - Weasyprint requirements

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#29]
Ref: https://github.com/inventree/InvenTree/issues/1089

- Weasyprint prerequisites may not be installed on a given system.
- As part of the "install" script, maybe these can be checked, and the proper packages can be automatically installed, based on the OS
- Or, just add an instruction linking to the install guide for weasyprint

**Comment by eeintech** [comment]
@SchrodingersGat Reading through the `weasyprint` installation docs, they look to have different requirements depending on the system so it makes it difficult to add checks to the "install" script. I think we're better off bringing them to the user's attention in the InvenTree docs (see #31).

**Comment by SchrodingersGat** [comment]
Yes it does look complicated. I'm looking at switching to [xhtml2pdf](https://pypi.org/project/django-xhtml2pdf/) which just seems to require PIP and does much the same thing.

The PDF exporting functionality is basically non-existent at the moment so potentially a change of the underlying library wouldn't be too difficult.
