### ISSUE TITLE
Barcode Documentation

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#327]
Need to add an "overview" section documenting the available barcode functionality. 

- Supported barcode types
- "native" barcodes vs custom barcodes
- navigation links out to the "specific" barcode actions
- plugin support

Specifically address the recent refactor: https://github.com/inventree/InvenTree/pull/3640

**Comment by matmair** [comment]
@SchrodingersGat seems to be something that comes up from time to time.
