### ISSUE TITLE
Docker installation on Windows 10 wsl

### ISSUE THREAD

**Issue by angelosne** [inventree/inventree-docs#336]
Hi I just installed without problem the production docker on my arch linux and I wanted to install it to my win 10 work machine.
I set up all the required files in one folder and when I type
`docker-compose run inventree-server invoke update`
I get an error
`Invalid interpolation format for "environment" option in service "inventree-db": "POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}"`

In my env file I have completed INVENTREE_DB_USER and all the other requirements
My WSL is an UBUNTU 18.04 LTS fully updated. Windows 10 is also fully updated

**Comment by SchrodingersGat** [comment]
Hey @angelosne this repo is for the documentation - in future please direct any queries to the [InvenTree issues page](https://github.com/inventree/InvenTree/issues)

Regarding this issue:

- Is the `.env` file in the same directory as your `docker-compose.yml` file?
- Can you link your `.env` and `docker-compose.yml` files here?

**Comment by angelosne** [comment]
Hi SchrodingersGat!

`this repo is for the documentation - in future please direct any queries to the [InvenTree issues page](https://github.com/inventree/InvenTree/issues)`
Sorry I didn't notice that , should I open it there and delete it here?

So I have the E:\Docker\Inventree and in this folder I have the 3 files (env, docker-compose, ngnix.prod.conf) and I created 2 folders (media and static)

My docker-compose is unchanged from the original 

[Zipped files](https://github.com/inventree/inventree-docs/files/9218230/Archive.zip)

**Comment by SchrodingersGat** [comment]
Unrelated but you can't do this:

![image](https://user-images.githubusercontent.com/10080325/181729222-444d9474-9bfc-4ad8-9eac-0a8188a286ec.png)

The path E:\Docker\(etc) is not accessible (by name) inside the context of the docker container. Don't override any internal paths, just set `INVENTREE_EXT_VOLUME` and everything else will just work.

**Comment by SchrodingersGat** [comment]
What version of docker and docker compose are you running?

![image](https://user-images.githubusercontent.com/10080325/181729676-a8d729c0-aa75-4b12-94d2-78679b209a72.png)

**Comment by angelosne** [comment]
Yes I know it does not work this one. I was messing around reading the docs and I found that I only have to use the INVENTREE_EXT_VOLUME with the docker.

> Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3
> 
> docker-compose version 1.17.1, build unknown

I see you use powershell right?
I am using the wsl console (if I say it right). Is this a problem or makes a difference?

**Comment by angelosne** [comment]
I just saw that I am at WSL1 and also tried to run some docker commands and says the daemon is not running. I am going to fix that problems and will come back.

**Comment by SchrodingersGat** [comment]
If you are running docker desktop, then you should be running these commands from powershell, not WSL terminal

**Comment by angelosne** [comment]
As it seems my CPU (Q8400) is too old for this stuff (does not support SLAT) so it is no possibility to run docker. Sorry for the upset!

**Comment by SchrodingersGat** [comment]
>  so it is no possibility to run docker.

Well, that answers that then! :)
