### ISSUE TITLE
`0.8.2` was released but documentation link is broken

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-docs#363]
### Body of the issue

Navigate to: https://inventree.readthedocs.io/en/0.8.2/

![image](https://user-images.githubusercontent.com/4020546/187307848-ab04709e-91c4-47fd-a627-834297a53943.png)

![image](https://user-images.githubusercontent.com/4020546/187307883-c2000cab-a623-4fba-9518-43e1629fef9f.png)

**Comment by SchrodingersGat** [comment]
@eeintech thanks for reporting, I've addressed this now.
