### ISSUE TITLE
Update digital ocean image

### ISSUE THREAD

**Issue by SANCLA** [inventree/inventree-docs#367]
### Body of the issue

Hey everybody,

Fantastic work, thanks for putting in the effort.
In 1-2 weeks, I can perhaps contribute to documentation and perhaps translation.

For now, would it be possible to update the digital ocean image?
That would be great if possible!

Thanks, keep up the good work!

**Comment by matmair** [comment]
@SANCLA hi there!
The digital ocean is not part of this organisation. It is a 3rd party thing maintained by me. DO has several review steps and the new image keeps failing therefore it is not up to date right now.
