### ISSUE TITLE
Duplicates on export

### ISSUE THREAD

**Issue by SGennaro01** [inventree/inventree-docs#378]
After updating inventree from 0.1.8 to 0.8.3, i noticed a strange behavior exporting a csv, xls or xlsx with about a thousand serialized stock items. The problem is related to duplicated serials exported, but looking into the database there is only one serial related to that stock item.

In the attachments, you can find the csv exported from inventree with a test part called "Test 2" that has about a thousand serialized stock item. If you open it you will notice that an item is repeated 4 times, with the same id and serial.

In this case the duplicated stock item id is 8216

[InvenTree_StockItems_27-Oct-2022.csv](https://github.com/inventree/inventree-docs/files/9880743/InvenTree_StockItems_27-Oct-2022.csv)

**Comment by SchrodingersGat** [comment]
@SGennaro01 issues for the InvenTree software should really be raised over at https://github.com/inventree/inventree/issues

This repository is specifically for the InvenTree documentation.

What process are you following to export the records here? Note that `0.1.8` is quite old, there may be a bug with how records are being exported from this older version

**Comment by matmair** [comment]
@SGennaro01 you are using 0.8.3 when having the export error?

**Comment by SGennaro01** [comment]
> @SGennaro01 issues for the InvenTree software should really be raised over at https://github.com/inventree/inventree/issues
Sorry, can i move to the other repository?

@SGennaro01 you are using 0.8.3 when having the export error?

Yes, i'm using the 0.8.3.

**Comment by SchrodingersGat** [comment]
And what process are you using to export the data? Via the admin interface, or using the table data export tool in the web UI?

(screenshots here would be appreciated)

**Comment by SGennaro01** [comment]
I'm using the table data export tool of the web UI.

![image](https://user-images.githubusercontent.com/81356966/198529793-b2e99b0d-6f26-4117-bea2-2dc72724814e.png)
![image](https://user-images.githubusercontent.com/81356966/198529947-dfd7f2d8-907e-488e-a4ed-08e2f57eb536.png)

Changing the export format is not a solution, the duplicates are there even with the other formats. @SchrodingersGat

**Comment by SchrodingersGat** [comment]
Can you determine whether the duplicates are there when you are just accessing the data via the API (i.e. *not* exporting to a file)?

**Comment by SGennaro01** [comment]
Yes, sure I will do it as soon as possible.

**Comment by SchrodingersGat** [comment]
Thanks @SGennaro01 - not much we can do until we can reproduce the issue :)

**Comment by SchrodingersGat** [comment]
@SGennaro01 I'll close this issue out now - if you can provide any further information, please raise a new issue on the source code repository.
