### ISSUE TITLE
Backup dir - Formulation might be unclear

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-docs#382]
### Body of the issue

In this section: https://inventree.readthedocs.io/en/latest/start/config/#backup-file-storage
> By default, database and media backups are stored in the local directory /home/inventree/backup. This directory should be changed by specifying the backup_dir option in the config file based on the particular installation requirements.
>
> Alternatively this location can be specified with the INVENTREE_BACKUP_DIR environment variable.

I think the formulation is not clear, but I am not completely sure so I want to check before fixing the docs.

Without the `backup_dir` option in the config file, I am encountering this error:
``` bash
File ".../InvenTree/config.py", line 169, in get_backup_dir
raise FileNotFoundError('INVENTREE_BACKUP_DIR not specified')
```

Indeed the code is not checking for any "default" directory:
https://github.com/inventree/InvenTree/blob/9beefd09f75e32066be2e91c64f84e8f055a1b0b/InvenTree/InvenTree/config.py#L163

So the text should say instead:
> Database and media backups **require** a local folder for backup. This directory should be changed...

Or am I mistaken?

**Comment by matmair** [comment]
@eeintech your suggestion sounds right. No idea how that slipped by me.
Can you make a PR or should I?

**Comment by eeintech** [comment]
I have posted a PR :wink:
