### ISSUE TITLE
Discrepancies in Python versions

### ISSUE THREAD

**Issue by eeintech** [inventree/inventree-docs#383]
### Body of the issue

The official docs mention `Python 3.8` as the minimum Python version: https://inventree.readthedocs.io/en/latest/start/intro/#python-requirements

However, the contributing guide on the main repo show `Python 3.9`: https://github.com/inventree/InvenTree/blob/master/CONTRIBUTING.md#target-version

It seems like `Python 3.9` is indeed required as code lines like the following one:
https://github.com/inventree/InvenTree/blob/9beefd09f75e32066be2e91c64f84e8f055a1b0b/InvenTree/InvenTree/tasks.py#L156

would failed if ran with `Python 3.8`:
``` bash
File ".../InvenTree/tasks.py", line 156, in TaskRegister
    task_list: list[ScheduledTask] = []
TypeError: 'type' object is not subscriptable
```

**Comment by matmair** [comment]
@eeintech I'm starting to wonder how many places it still is mentioned. We already fixed a few places - I would recommend changing that section to be like the tipp [here](https://inventree.readthedocs.io/en/latest/start/install/#install-system-packages).

**Comment by eeintech** [comment]
Not sure how many places, in the doc repo this is the only mention I can find
