### ISSUE TITLE
APT Update Command 

### ISSUE THREAD

**Issue by rezafouladian** [inventree/inventree-docs#402]
The [install script documentation](https://github.com/inventree/inventree-docs/blob/master/docs/start/installer.md#updating-inventree) mentions running `apt update inventree`, however on Ubuntu this returns `The update command takes no arguments`.

Should this be something like `apt install inventree` or `apt install --only-upgrade inventree` instead?

**Comment by matmair** [comment]
@rezafouladian you are right, an update is en route.

**Comment by matmair** [comment]
@rezafouladian was your problem fixed by this?
