### ISSUE TITLE
Enable shorter install url

### ISSUE THREAD

**Issue by matmair** [inventree/inventree-docs#417]
It would be nice to have shorter install command to link to.

## Suggestion
We could add a redirect on the nameserver level for get.inventree.org to `https://raw.githubusercontent.com/InvenTree/InvenTree/master/contrib/install.sh`. That way the command would be
`wget -Nq get.inventree.org && bash install.sh`
instead of
`wget -Nq https://raw.githubusercontent.com/InvenTree/InvenTree/master/contrib/install.sh && bash install.sh`

**Comment by matmair** [comment]
@SchrodingersGat thoughts?

**Comment by SchrodingersGat** [comment]
Yeah this seems pretty reasonable. What sort of NS record would we need to achieve this?

**Comment by matmair** [comment]
@SchrodingersGat that depends on your nameserver provider. It is probably named redirect. DM me so we can figure it out.

**Comment by SchrodingersGat** [comment]
@matmair this is enable now - https://get.inventree.org

Can you submit a PR to update the installer docs accordingly? :)
