### ISSUE TITLE
Unable to login after installing inventree on digital ocean droplet

### ISSUE THREAD

**Issue by irfanharunk** [inventree/inventree-docs#422]
### Body of the issue

I installed a inventree on digitalocean under an assumption that once installed, I will be able to login using default username and password listed on 
https://inventree.org/demo.html

how can i login to inventree application, once it is installed, up and running

**Comment by matmair** [comment]
Hi there @irfanharunk !
Please use the main repo for reports in the future: https://github.com/inventree/inventree

Regarding your question:
As stated on the [marketplace page](https://marketplace.digitalocean.com/apps/inventree) and the pop-up after you deploy the app you need to open a console to your droplet to get you username and password. Those get generated on during deployment.
The logins on the demo page only work on the official instance or when you deploy the demo dataset.

**Comment by irfanharunk** [comment]
Thank you for your inputs and my apologies for not raising the issue in correct place ( I will do this if required). 

Can you please guide me regarding where to find the username and password once I'm logged in into the droplet. I was not able to spot this information on the marketplace page

**Comment by matmair** [comment]
![grafik](https://user-images.githubusercontent.com/66015116/213298808-4a0ae092-9875-4b28-8b2d-4ed9644a4cbc.png)
The first thing you are presented with when logging in the first time is a MOTD message showing a username and password. After that, it is not shown again for security reasons.
Check /etc/inventree for a password file. If you have a new.-ish (0.9.0 or higher) version the info is backed up there.
