### ISSUE TITLE
Dev server crashes without demo data

### ISSUE THREAD

**Issue by ktyurin** [inventree/inventree-docs#429]
$> git clone https://github.com/inventree/InvenTree.git && cd InvenTree
$> docker compose run inventree-dev-server invoke install
$> docker compose run inventree-dev-server invoke setup-test

If the third command is not executed dev server crashes with errors provided beneath.
Is it an expected behavior? Because from the documentation I got an impression that filling the system with test data is an optional thing, like if one want to pre-populate DB with some data they should call it otherwise they get just clean DB

inventree-dev-db      | 2023-01-28 09:52:51.896 UTC [45] ERROR:  relation "common_inventreesetting" does not exist at character 112
inventree-dev-db      | 2023-01-28 09:52:51.896 UTC [45] STATEMENT:  SELECT "common_inventreesetting"."id", "common_inventreesetting"."value", "common_inventreesetting"."key" FROM "common_inventreesetting" WHERE UPPER("common_inventreesetting"."key"::text) = UPPER('SERVER_RESTART_REQUIRED') ORDER BY "common_inventreesetting"."id" ASC LIMIT 1

inventree-dev-worker  | Traceback (most recent call last):
inventree-dev-worker  |   File "/home/inventree/data/env/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
inventree-dev-worker  |     return self.cursor.execute(sql, params)
inventree-dev-worker  | psycopg2.errors.UndefinedTable: relation "label_stockitemlabel" does not exist
inventree-dev-worker  | LINE 1: SELECT (1) AS "a" FROM "label_stockitemlabel" WHERE "label_s...

**Comment by SchrodingersGat** [comment]
@ktyurin please run `invoke update` instead of `invoke install`. Your command sequence here is not running the required database migrations.

Ref: https://docs.inventree.org/en/latest/faq/#errors-during-inventree-update

Please try this and LMK if that works for you.

**Comment by ktyurin** [comment]
@SchrodingersGat thanks! The proposed sequence works!

**Comment by matmair** [comment]
Closing as solved
