### ISSUE TITLE
slight grammatical error on documentation

### ISSUE THREAD

**Issue by sumanth-1022** [inventree/inventree-docs#456]
### Body of the issue

Middleware
Custom middleware layers can specified here.

can you please check and edit the documentation for this part? I believe it is "custom middleware layers can be specified here)

**Comment by SchrodingersGat** [comment]
@sumanth-1022 please provide a link to the particular page

**Comment by sumanth-1022** [comment]
apologies. -> https://docs.inventree.org/en/latest/start/config/ -> at the end.
