### ISSUE TITLE
Update docs to match new menubar style

### ISSUE THREAD

**Issue by SchrodingersGat** [inventree/inventree-docs#72]
Previously used "tab" navigation style, now has migrated to "menubar"

- Need to update screenshots
- There are also many more 'views' available - document each one!

- [ ] Part
- [ ] Part Category
- [ ] Stock Item
- [x] Company
- [ ] Supplier Part
- [ ] Build Order
- [ ] Purchase Order
- [ ] Sales Order

**Comment by eeintech** [comment]
@SchrodingersGat Started this with #174, which I believe covers "Part" and "Part Category"

**Comment by eeintech** [comment]
I think the "Companies" doc is looking good with the merge of #158 what do you think?

**Comment by eeintech** [comment]
Added build refresh into #175

**Comment by eeintech** [comment]
Refresh completed in #176
